### ISSUE TITLE
packaging for cocoa pods and spm

### ISSUE THREAD

**Issue by tbachmor-letsdev** [eunid/netid-sdk-ios#127]

**Comment by asr-enid** [comment]
bundle references must e updated to Bundle.module in all UI classes and text util, in order for the assets to be found within the package at runtime

**Comment by asr-enid** [comment]
Building against the pod works fine, but at runtime the bundle identifier cannot be found 

https://github.com/eunid/netid-sdk-ios/blob/89053f30847f1b1b577a3433b1b6c7d48ddf3159/Sources/NetIdMobileSdk/api/NetIdService.swift#L565

This results in a exception because the Bundle is nil and we try to unwrap it. 

I think we need to extend the podspec to set the propoer bundle id for the pod (its seems its set to some other bundle id by cocoa)

```
# in .podspec
s.info_plist = {
  'CFBundleIdentifier' => 'de.netid.mobile.sdk.NetIdMobileSdk'
}
```

**Comment by asr-enid** [comment]
The approach is generally okay, but the bundle resolution for the pod build  does not work for me (ressource bundle is not found although present in the SDK Framework with the new pod config)

https://github.com/eunid/netid-sdk-ios/blob/397a47a35ba05b914d33c1aaae8365c53322cb8a/Sources/NetIdMobileSdk/api/NetIdService.swift#L567

_allBundles_ does not contain the right Bundle that contains the SDK Framework thus the ressource is not found. 

The implementation in this branch work in all cases for me (SPM, XCODE and pods, both simulator and on a physical phone)

https://github.com/eunid/netid-sdk-ios/tree/pod_fix_clean

https://github.com/eunid/netid-sdk-ios/blob/a466c595075097baff6609276989c5a8465230cb/Sources/NetIdMobileSdk/api/NetIdService.swift#L564

Same approach to resolve the bundle as seen here:

https://github.com/liamnichols/ListItemFormatter/pull/39/files

**Comment by asr-enid** [comment]
Additional benefit, no loops and only called once
